name: remote ssh command

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 5m
        script: |
          cd /markdown-nice-api
          git pull origin master
          mvn clean package
          java -jar target/demo.jar
