name: remote ssh command
on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 10m
        script: |
          sudo fuser -k -n tcp 8080
          cd /home/mdnice/markdown-nice-api
          git pull origin master
          mvn clean package
          cd target
          nohup java -jar demo-0.0.1-SNAPSHOT.jar >> ./markdown-nice-api.log &
